[versions]
jackson = "2.21.1"
spring-boot = "4.0.7"

[plugins]
lombok = { id = "io.freefair.lombok", version = "9.5.0" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-boot-aot = { id = "org.springframework.boot.aot", version.ref = "spring-boot" }
spring-dependencies = { id = "io.spring.dependency-management", version = "1.1.7" }
springdoc = { id = "org.springdoc.openapi-gradle-plugin", version = "1.9.0" }
openapi = { id = "org.openapi.generator", version = "7.23.0" }
loom = { id = "net.fabricmc.fabric-loom", version = "1.17-SNAPSHOT" }
spotless = { id = "com.diffplug.spotless", version = "8.8.0" }

[libraries]
springdoc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "3.0.2" }
spring-boot-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc" }
spring-boot-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test" }
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version = "2.21" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jakarta-annotations = { group = "jakarta.annotation", name = "jakarta.annotation-api", version = "2.1.1" }

devauth = { group = "me.djtheredstoner", name = "DevAuth-fabric", version = "1.2.1" }
minecraft = { group = "com.mojang", name = "minecraft", version = "26.1.2" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.19.3" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.154.2+26.1.2" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version = "4.5.14" }
